// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace sss {

class RpcWork final {
 public:
  static constexpr char const* service_full_name() {
    return "sss.RpcWork";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RemoteCall(::grpc::ClientContext* context, const ::sss::Request& request, ::sss::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sss::Response>> AsyncRemoteCall(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sss::Response>>(AsyncRemoteCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sss::Response>> PrepareAsyncRemoteCall(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sss::Response>>(PrepareAsyncRemoteCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sss::Request, ::sss::Response>> RemoteStreamCall(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sss::Request, ::sss::Response>>(RemoteStreamCallRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sss::Request, ::sss::Response>> AsyncRemoteStreamCall(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sss::Request, ::sss::Response>>(AsyncRemoteStreamCallRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sss::Request, ::sss::Response>> PrepareAsyncRemoteStreamCall(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sss::Request, ::sss::Response>>(PrepareAsyncRemoteStreamCallRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RemoteCall(::grpc::ClientContext* context, const ::sss::Request* request, ::sss::Response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RemoteCall(::grpc::ClientContext* context, const ::sss::Request* request, ::sss::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void RemoteCall(::grpc::ClientContext* context, const ::sss::Request* request, ::sss::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void RemoteStreamCall(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sss::Request,::sss::Response>* reactor) = 0;
      #else
      virtual void RemoteStreamCall(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::sss::Request,::sss::Response>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sss::Response>* AsyncRemoteCallRaw(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sss::Response>* PrepareAsyncRemoteCallRaw(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::sss::Request, ::sss::Response>* RemoteStreamCallRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sss::Request, ::sss::Response>* AsyncRemoteStreamCallRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sss::Request, ::sss::Response>* PrepareAsyncRemoteStreamCallRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RemoteCall(::grpc::ClientContext* context, const ::sss::Request& request, ::sss::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sss::Response>> AsyncRemoteCall(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sss::Response>>(AsyncRemoteCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sss::Response>> PrepareAsyncRemoteCall(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sss::Response>>(PrepareAsyncRemoteCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::sss::Request, ::sss::Response>> RemoteStreamCall(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::sss::Request, ::sss::Response>>(RemoteStreamCallRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sss::Request, ::sss::Response>> AsyncRemoteStreamCall(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sss::Request, ::sss::Response>>(AsyncRemoteStreamCallRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sss::Request, ::sss::Response>> PrepareAsyncRemoteStreamCall(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sss::Request, ::sss::Response>>(PrepareAsyncRemoteStreamCallRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RemoteCall(::grpc::ClientContext* context, const ::sss::Request* request, ::sss::Response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RemoteCall(::grpc::ClientContext* context, const ::sss::Request* request, ::sss::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void RemoteCall(::grpc::ClientContext* context, const ::sss::Request* request, ::sss::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void RemoteStreamCall(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::sss::Request,::sss::Response>* reactor) override;
      #else
      void RemoteStreamCall(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::sss::Request,::sss::Response>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sss::Response>* AsyncRemoteCallRaw(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sss::Response>* PrepareAsyncRemoteCallRaw(::grpc::ClientContext* context, const ::sss::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::sss::Request, ::sss::Response>* RemoteStreamCallRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::sss::Request, ::sss::Response>* AsyncRemoteStreamCallRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::sss::Request, ::sss::Response>* PrepareAsyncRemoteStreamCallRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RemoteCall_;
    const ::grpc::internal::RpcMethod rpcmethod_RemoteStreamCall_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RemoteCall(::grpc::ServerContext* context, const ::sss::Request* request, ::sss::Response* response);
    virtual ::grpc::Status RemoteStreamCall(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sss::Response, ::sss::Request>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RemoteCall() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteCall(::grpc::ServerContext* context, ::sss::Request* request, ::grpc::ServerAsyncResponseWriter< ::sss::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RemoteStreamCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RemoteStreamCall() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RemoteStreamCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteStreamCall(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sss::Response, ::sss::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteStreamCall(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::sss::Response, ::sss::Request>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RemoteCall<WithAsyncMethod_RemoteStreamCall<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RemoteCall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::sss::Request, ::sss::Response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::sss::Request* request, ::sss::Response* response) { return this->RemoteCall(context, request, response); }));}
    void SetMessageAllocatorFor_RemoteCall(
        ::grpc::experimental::MessageAllocator< ::sss::Request, ::sss::Response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::sss::Request, ::sss::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RemoteCall(
      ::grpc::CallbackServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RemoteCall(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RemoteStreamCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_RemoteStreamCall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::sss::Request, ::sss::Response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->RemoteStreamCall(context); }));
    }
    ~ExperimentalWithCallbackMethod_RemoteStreamCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteStreamCall(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sss::Response, ::sss::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::sss::Request, ::sss::Response>* RemoteStreamCall(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::sss::Request, ::sss::Response>* RemoteStreamCall(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_RemoteCall<ExperimentalWithCallbackMethod_RemoteStreamCall<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_RemoteCall<ExperimentalWithCallbackMethod_RemoteStreamCall<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RemoteCall() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RemoteStreamCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RemoteStreamCall() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RemoteStreamCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteStreamCall(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sss::Response, ::sss::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RemoteCall() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RemoteStreamCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RemoteStreamCall() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RemoteStreamCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteStreamCall(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sss::Response, ::sss::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoteStreamCall(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(1, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RemoteCall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RemoteCall(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* RemoteCall(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* RemoteCall(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RemoteStreamCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_RemoteStreamCall() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->RemoteStreamCall(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_RemoteStreamCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoteStreamCall(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::sss::Response, ::sss::Request>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* RemoteStreamCall(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* RemoteStreamCall(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RemoteCall : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RemoteCall() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::sss::Request, ::sss::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::sss::Request, ::sss::Response>* streamer) {
                       return this->StreamedRemoteCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RemoteCall() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RemoteCall(::grpc::ServerContext* /*context*/, const ::sss::Request* /*request*/, ::sss::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemoteCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sss::Request,::sss::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RemoteCall<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RemoteCall<Service > StreamedService;
};

}  // namespace sss


#endif  // GRPC_message_2eproto__INCLUDED
